# Generated by Django 6.0.2 on 2026-02-14 15:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
                'indexes': [models.Index(fields=['slug'], name='learning_co_slug_b348c5_idx'), models.Index(fields=['is_active'], name='learning_co_is_acti_d5cb81_idx')],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('cover_image_path', models.CharField(blank=True, max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='learning.course')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LessonCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('english', models.CharField(max_length=255)),
                ('uzbek', models.CharField(max_length=255)),
                ('pronunciation', models.CharField(blank=True, max_length=255)),
                ('mnemonic_example', models.TextField(blank=True)),
                ('translation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='learning.lesson')),
            ],
            options={
                'ordering': ['order', 'english'],
            },
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['slug'], name='learning_le_slug_39551e_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['course', 'order'], name='learning_le_course__30756f_idx'),
        ),
        migrations.AddIndex(
            model_name='lessoncard',
            index=models.Index(fields=['lesson', 'order'], name='learning_le_lesson__7c07f4_idx'),
        ),
        migrations.AddIndex(
            model_name='lessoncard',
            index=models.Index(fields=['lesson', 'english'], name='learning_le_lesson__a0a64e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lessoncard',
            unique_together={('lesson', 'english')},
        ),
    ]
